.TH "SHMIDCAT" "1" "3.0.8" "Anthony Bybell" "Shared Memory Trampoline"
.SH "NAME"
.LP 
shmidcat \- Copies stdin/file to a shared memory block for \fIgtkwave\fP(1)
.SH "SYNTAX"
.LP 
shmidcat [\fIVCDFILE\fP]
.SH "DESCRIPTION"
.LP 
Copies either the file specified at the command line or stdin (if no file specified) line by line to a shared memory block.  stdout will contain a shared memory ID which should be passed on to \fIgtkwave\fP(1).
.SH "EXAMPLES"
.LP 
To run this program the standard way type:
.TP 
cat whatever.vcd | shmidcat
The shared memory ID is emitted to stdout.
.TP 
shmidcat whatever.vcd | gtkwave \-v \-I whatever.sav
GTKWave directly grabs the ID from stdin.
.SH "LIMITATIONS"
This program is mainly for illustrative and testing purposes only.  Its primary use is for people who wish to write 
interactive VCD dumpers for \fIgtkwave\fP(1) as its source code may be examined, particularly the emit_string() function.
It can also be used to test if an existing VCD file will load properly in interactive mode.  
Note that it can also be used to redirect
VCD files which are written into a pipe to \fIgtkwave\fP(1) in a non-blocking fashion.
.LP
.SH "AUTHORS"
.LP 
Anthony Bybell <bybell@rocketmail.com>
.SH "SEE ALSO"
.LP 
\fIgtkwave\fP(1)
