# A workflow to build and test GTKWave on all major supported platforms.

name: CI

# Immediate TODOs:
# TODO: Do we like the current structure of the linux-x86-64 bundle?
# TODO: Remove the x86-64 bundle requirement of manual libjudydebian1 installation.
# TODO: Consider checking in the linux x86-64 launcher instead of recreating it.concurrency: 
# TODO: Can we change the build scripts to output to 'bin' dirs instead of 'src' dirs?

# For latter:
# TODO: Add a build job for win x86-64.
# TODO: Add a build job for macOS x86-64.
# TODO: Create a pre-release with the build artifacts of all the platforms.
# TODO: Consider scanning the exported artifacts with clamav
# TODO: After stabilization, remove the debugging only steps.

on:
  # Run on push.
  push:
    branches: ["master"]

  # Run on a pull request.
  pull_request:
    branches: ["master"]

  # Allow to run manually
  workflow_dispatch:

jobs:
  build-linux-x86-64:
    name: Build (linux-x86-64)
    # NOTE: Using ubuntu-latest here links to a newer glibc that is
    # not backward compatible with Ubuntu LTS 24.04. If additional backward
    # compatibility will be needed, consider to demote to ubuntu-20.04.
    runs-on: ubuntu-22.04

    env:
      # The name of the top wrapper dir within the bundle archive artifact.
      BUNDLE: "gtkwave-x86-64"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
              gperf \
              desktop-file-utils \
              libgtk-3-dev \
              libgtk-4-dev \
              libjudy-dev \
              libgirepository1.0-dev \
              libjson-glib-dev

      - name: Install meson
        run: |
          pip install meson ninja

      - name: Setup meson build
        run: |
          meson setup build

      - name: Compile GTKWave
        run: |
          meson compile -C build

      # - name: Show the build directory tree
      #   run: |
      #     tree -d build

      # - name: Show the build directory full tree
      #   run: |
      #     tree build

      # - name: Archive the build folder (for debugging)
      #   run: |
      #     tar -czvf gtkwave-linux-x86-64-build-dump.tar.gz build

      # - name: Upload the build archive as an artifact (for debugging)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: linux-build-folder1
      #     path: gtkwave-linux-x86-64-build-dump.tar.gz
      #     if-no-files-found: error
      #     retention-days: 14

      - name: Create the file bundle
        run: |
          set -x

          # Copy a directory tree preserving attributes and symlinks.
          # We assume that the symlinks are within the directory tree.
          cp_dir="rsync -aHAX --no-inc-recursive"
          cp_file="cp --preserve=all"

          mkdir build/$BUNDLE

          # Copy selected directories.
          $cp_dir build/lib/ build/$BUNDLE/lib/
          $cp_dir build/subprojects/ build/$BUNDLE/subprojects/

          # Copy a subset of build/src to the bundle
          # NOTE: Renaming the 'src' dirs to 'bin' break the lib references.
          mkdir build/$BUNDLE/src
          $cp_file build/src/gtkwave build/$BUNDLE/src/gtkwave
          $cp_file build/src/twinwave build/$BUNDLE/src/twinwave
          $cp_dir build/src/helpers/ build/$BUNDLE/src/helpers/

          # Fine-tune the bundle
          rm -rf build/$BUNDLE/lib/libgtkwave/test
          rm -rf build/$BUNDLE/subprojects/libfst/tests

      # NOTE: We tried to use this 'find' commands but it fails.
      # find $bundle_dir -type d -name '*.p' -exec rm -rf {} \;
      - name: Delete bundle's *.p sub-directories.
        shell: python
        run: |
          import shutil
          from pathlib import Path
          root = Path("build/${{ env.BUNDLE }}")
          for path in sorted(root.rglob('*')):
              if path.name.endswith(".p"):
                  print(f'Deleting: {path}')
                  shutil.rmtree(path)

      - name: Add to the bundle a launcher file
        run: |
          cat > build/$BUNDLE/gtkwave << 'EOF'
          #!/usr/bin/env bash
          SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
          exec "$SCRIPT_DIR/src/gtkwave" "$@"
          EOF
          chmod +x build/$BUNDLE/gtkwave
          cat -n build/$BUNDLE/gtkwave

      - name: Show the bundle tree
        run: |
          tree build/$BUNDLE

      - name: Tar the bundle directory
        run: |
          pushd build
          tar -czvf gtkwave-linux-x86-64-bundle.tar.gz $BUNDLE
          popd

      - name: Upload bundle archive as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: gtkwave-linux-x86-64-bundle
          path: build/gtkwave-linux-x86-64-bundle.tar.gz
          if-no-files-found: error
          retention-days: 14

      - name: Run tests
        run: |
          meson test -C build -v

  build-macos-arm64:
    name: Build (macos-arm64)
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          brew install \
              meson \
              gtk+3 \
              gtk4 \
              gtk-mac-integration \
              gobject-introspection \
              shared-mime-info \
              desktop-file-utils \
              json-glib \
              librsvg

      - name: Setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.3.0

      - name: Setup meson build script
        run: meson setup build

      - name: Compile GTKWave
        run: meson compile -C build

      - name: Run tests
        run: meson test -C build -v

      - name: Build and install GTKWave.app
        run: |
          sh ./macos/build.sh

          # Export the .app dir location.
          echo "APP_DIR=${HOME}/Applications/GTKWave.app" >> "$GITHUB_ENV"

      - name: Archive Applications/GTKWave.app
        run: |
          # Create the archive under ./build
          # Use ditto instead of zip to make sure resources forks are preserved in the zip archive.
          ditto -c -k --sequesterRsrc --keepParent "${APP_DIR}" build/GTKWave.app.zip
          ls -lh build/GTKWave.app.zip

      # NOTE: If downloading, remember to run 'xattr -c macos-gtkwave-app.zip'
      # to remove the quarantine flag.
      - name: Upload the archived GTKWave.app archive artifact
        uses: actions/upload-artifact@v4
        with:
          # NOTE: Github adds a zip layer and appends '.zip' to the name.
          name: gtkwave-macos-arm64-app
          path: build/GTKWave.app.zip
          if-no-files-found: error
          retention-days: 14
